import Header from '@/components/Header'
import Hero from '@/components/Hero'
import Post from '@/components/Post'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-6xl mx-auto">
        <Header />
        <Hero />
        <section className='grid  md:grid-cols-2 lg:grid-cols-3 my-10 gap-4 mx-4'>
        <Post profile='https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGRldmVsb3BlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60' img='https://images.unsplash.com/photo-1622675363311-3e1904dc1885?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGRldmVsb3BlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60' title="Vangog" text="lorem gad if too maony melon fire fabric stone rock lee name saeed pool beer drink"/>
        <Post img="https://images.unsplash.com/photo-1562813733-b31f71025d54?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGNvZGluZ3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60" profile='https://images.unsplash.com/photo-1629904853893-c2c8981a1dc5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGRldmVsb3BlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60' title="Picaso" text="lorem gad if too maony melon fire fabric stone rock lee name saeed pool beer drink"/>
        <Post img="https://media.istockphoto.com/id/1451456915/photo/female-freelance-developer-coding-and-programming-coding-on-two-with-screens-with-code.jpg?b=1&s=170667a&w=0&k=20&c=7QL_-R6HTGHCYt37C8NyjuW6mIiJeQhDVgW8i_6l4Vk=" profile='https://images.unsplash.com/photo-1602992708529-c9fdb12905c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGRldmVsb3BlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60' title="Elon " text="lorem gad if too maony melon fire fabric stone rock lee name saeed pool beer drink"/>
        <Post img="https://media.istockphoto.com/id/537331500/photo/programming-code-abstract-technology-background-of-software-deve.jpg?b=1&s=170667a&w=0&k=20&c=iQE4in2blXsYoRYjoX7F8e4AFF6kOaE-TZiVNMPQ5kI=" profile='https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGRldmVsb3BlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60' title="Khavier" text="lorem gad if too maony melon fire fabric stone rock lee name saeed pool beer drink"/>
        <Post img="https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGNvZGluZ3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" profile='https://media.istockphoto.com/id/1469706255/photo/night-reflection-and-neon-with-woman-at-computer-for-programmer-cloud-computing-and-software.jpg?b=1&s=170667a&w=0&k=20&c=YFrtEbGxKkNfibjr3ejIjXosJUKf0BnobuRnLoeFeg0=' title="Salman" text="lorem gad if too maony melon fire fabric stone rock lee name saeed pool beer drink"/>
        <Post img="https://images.unsplash.com/photo-1580894732444-8ecded7900cd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGNvZGluZ3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60" profile='https://media.istockphoto.com/id/1366415117/photo/computer-programmer-working-on-new-software.jpg?b=1&s=170667a&w=0&k=20&c=ero_juKcMIQMp2kDGOjFFm60rNWltARywKTfqC4jipo=' title="Margaret" text="lorem gad if too maony melon fire fabric stone rock lee name saeed pool beer drink"/>
        </section>
      </main>
    </>
  )
}
